"""Model asset declarations for jumper.

A module of its own that **does not import mjlab**: the four jumper tasks'
`__init__.py` need the asset path at registration time, and registration happens
during `import tasks`. Taking it from `constants.py` would pull mjlab / torch /
mujoco in with it and void the guarantee that `--list` stays lightweight (see
"why configs are lazy" in tasks/registry.py).

`constants.py` takes `JUMPER_XML` from here too, so the path has a single source of
truth.
"""

from __future__ import annotations

from pathlib import Path

from ...paths import ASSETS_DIR
from ...registry import AssetSpec

#: The default model, generated by `assets/jumper/tools/build_jumper.py`.
JUMPER_XML: Path = ASSETS_DIR / "jumper" / "jumper.xml"

#: The servo specification, and **load-bearing**: `common/actuator.py` reads the
#: torque-speed curve out of it at import, so the numbers the hardware was
#: measured at are the numbers the simulation runs on, with no second copy to
#: drift.
MOTOR_CONFIG: Path = ASSETS_DIR / "jumper" / "motor" / "motor_config.yaml"

#: The camera module: the drawing's optics, and the eye offset the mount uses.
#: Load-bearing -- `assets/jumper/tools/build_jumper.py` reads the orientation, the
#: vertical field of view and the resolution out of it when it writes the
#: `onboard` camera onto `camera_link`, and the `tof` block when it writes the
#: dToF's camera onto `tof_sensor_link`, so there is no second copy of them.
#:
#: **The pose is the model's, not this file's.** V1.6 carries the housing as a real
#: link and the URDF places it; `camera_rig.position_m` is the pre-V1.6 guess, kept
#: only because the ToF extrinsics were written against it and marked
#: `superseded_by_model`. It was 20 mm short, 14 mm off the centreline and 21 mm
#: too high.
CAMERA_CONFIG: Path = ASSETS_DIR / "jumper" / "camera" / "camera_config.yaml"

#: The dToF's measurement model -- accuracy, uniformity, temporal noise, detection
#: rate, frame rate -- from the VL53L9CX datasheet. Load-bearing:
#: `tasks/jumper/common/tof.py` applies it to every zone the sensor reports.
TOF_NOISE_CONFIG: Path = ASSETS_DIR / "jumper" / "camera" / "tof_noise_config.yaml"

#: The asset table shared by the four jumper tasks, for `--model` to select by name.
JUMPER_ASSETS: tuple[AssetSpec, ...] = (
    AssetSpec(
        name="jumper",
        path=JUMPER_XML,
        description="22-DoF heterogeneous hexapod (Liuzu V1.6), mesh collision "
                    "throughout -- link hulls not yet decimated",
    ),
)

__all__ = ["CAMERA_CONFIG", "JUMPER_XML", "JUMPER_ASSETS", "MOTOR_CONFIG", "TOF_NOISE_CONFIG"]
