"""Load the jump reference motion and give interpolated lookups over
continuous time.

The reference motion is a **recorded MuJoCo rollout** generated by kk-rl-lab's
`gen_jump_ref.py` outside `assets/jumper/tools/` -- it already satisfies gravity,
contact and the 2 N-m torque limit, so it is a target the policy can actually
reach and a full-score exp-kernel reward is physically attainable.

Ported from kk-rl-lab `tasks/hexa_5d/jump/mdp/reference.py`; two things had to be
done right when bringing it over:

* **Joint order**. The npz stores joints in MJCF actuator order (this project's
  jumper.xml matches it, but we do not rely on that coincidence): load time applies
  a single permutation by entity joint name, after which downstream code need not
  care. A missing joint is a hard error, not a silent misalignment.
* **Frame**. Foot positions are recorded in the MJCF world frame and drift with
  the base; load time converts them to the **base frame**, so the imitation reward
  compares leg geometry rather than where the robot happens to be.

Time semantics: the npz carries a pre-go preparatory stand (``t_go``); ``index_of``
clamps negative times to the go frame (whose pose is the stand), so an env waiting
for the command is scored as "stand still".
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch

from mjlab.utils.lab_api.math import quat_apply_inverse

#: Where this task's reference motions live. Under the task rather than in
#: `assets/`: `assets/jumper/` is the robot -- the model XML and the meshes every
#: task loads -- while a recorded jump is material only `jumper.jump` can use. Same
#: split `jumper.dance` makes with its `media/` directory.
REF_DIR: Path = Path(__file__).resolve().parent.parent / "ref"

#: Default reference motion. From kk-rl-lab
#: `assets/hexa_5d/jump_ref/high_jump_flat.npz`, kept under the name it was
#: generated with rather than a neutral one: it replaced `high_jump.npz`, and a
#: reference swapped under a shared name is a task that jumps differently with
#: nothing saying so.
#:
#: 368 frames, 1.47 s, rise 0.141 m, tilt 0.076 rad. Lower and less upright than
#: the one it replaced (0.162 m, 0.037 rad) and generated against the motor's
#: **torque-speed envelope** -- `meta["motor"]`, peak 1.7464 N*m, which is this
#: robot's `EFFORT_LIMIT` exactly. The old one had a flat `tau_limit` of 2.0 and
#: no envelope, so some of the height it reached was torque the motors cannot
#: deliver at speed.
#:
#: **The joint names are this robot's; the recording is the generator's.**
#: `gen_jump_ref.py` loads a model from before the V1.6.1 naming, so the file
#: arrived saying `LF_shoulder_yaw_joint`, `LM_hip_joint` and so on. Those were
#: relabelled to `<Leg>_J<n>_joint` in `meta["joint_order"]` and in the keys of
#: `meta["stand_pose"]`, and nothing else was touched: every array is the
#: generator's bytes, and this file differs from kk-rl-lab's in `meta.npy` alone.
#:
#: The rename is positional -- `shoulder_yaw shoulder_pitch elbow wrist finger` are
#: `J0`..`J4` on the arms, `hip knee ankle` are `J0`..`J2` on the legs -- and was
#: checked against both models rather than read off the names: the same 22 hinges
#: in the same order, each pair on the same axis in the base frame (cos 1.00000),
#: at the same depth in its chain and with the same range, bar the two grippers,
#: which now reach 0.1 rad past the zero they used to stop at. `J1` is the arms'
#: pitch and the legs' knee, which are different axes, so nothing may collapse the
#: two -- see `tasks/jumper/common/mdp/symmetry.py`. A reference taken from the
#: generator later arrives on the old names and needs the same relabelling before
#: it goes into `ref/`; loaded as it comes, it stops at `JumpReference`'s
#: missing-joint check.
#:
#: `meta["ik_ee"]` still names the generator's bodies (`LF_F_Link`,
#: `LM_toe_tip_link`). Those are not a rename: the front foot has been three
#: different bodies across three exports, so there is no successor to write in --
#: see `tests/test_jump_reference.py::test_foot_order_matches_legs`.
#:
#: **What the names do not fix.** They are only the part that fails loudly. The
#: model has moved underneath the recording as well: against
#: `kk-rl-lab/assets/hexa_5d/mjcf/robot.mjcf`, the model `gen_jump_ref.py` loads,
#: today's robot is 2.543 kg against 3.007, its `base_link` is 0.886 kg against
#: 1.080 with the COM 5.8 mm lower, and the leg mounts have moved by up to 11.6 mm
#: (`LF_J0`) -- so the feet sit 8 to 17 mm from where this rollout put them, in the
#: base frame, at every frame. The joint axes and the topology are unchanged. That
#: makes this a reference whose *shape* is right and whose torque feasibility was
#: established on a robot 15% heavier, which is a weaker claim than the docstring
#: above makes; regenerating it needs
#: `kk-rl-lab/assets/hexa_5d/gen_jump_ref.py --optimize`, warm-started from
#: `meta["params"]`, against a model taught these names.
JUMP_REF_NPZ = REF_DIR / "high_jump_flat.npz"


class JumpReference:
    """Reference trajectory resident on device, linearly interpolated at
    continuous frame indices."""

    def __init__(self, path: Path, device: str, joint_names: list[str]):
        d = np.load(path, allow_pickle=True)
        meta = json.loads(str(d["meta"]))
        src = meta["joint_order"]
        missing = [n for n in joint_names if n not in src]
        if missing:
            raise ValueError(
                f"[jump-ref] {path.name} is missing joints {missing}; "
                f"npz joint_order={src}"
            )
        perm = [src.index(n) for n in joint_names]

        t = torch.as_tensor(d["t"], dtype=torch.float32, device=device)
        self.n = int(t.numel())
        self.rec_hz = float(meta["rec_hz"])
        self.dt = 1.0 / self.rec_hz
        self.t_go = float(meta["t_go"])
        self.go_frame = int(meta["go_frame"])
        self.duration = float(t[-1].item())
        self.span = self.duration - self.t_go
        self.stand_base_z = float(meta["stand_base_z"])
        self.meta = meta

        def f(k):
            return torch.as_tensor(d[k], dtype=torch.float32, device=device)

        self.path = path
        self.joint_names = list(joint_names)
        self.q = f("q")[:, perm]
        self.qd = f("qd")[:, perm]
        # q_cmd is the position command the recorded controller actually sent
        # (200 Hz); q is the actual state with PD lag. During the fast extension
        # the two differ by 0.3 rad on average and 2.2 rad at peak -- the residual
        # action baseline must use q_cmd (zero action = exactly reproduces the
        # recorded controller), while the tracking reward uses q (the motion to
        # reproduce).
        self.q_cmd = f("q_cmd")[:, perm]
        self.control_hz = float(meta["control_hz"])
        self.base_pos = f("base_pos")
        self.base_quat = f("base_quat")
        self.base_lin_vel = f("base_lin_vel")

        # The contact schedule is rebuilt from foot geometric height rather than the
        # npz's contact channel: that one is recorded at a 1 N force threshold, so
        # the middle legs unloading during the pre-squat (foot z not moving at all,
        # force < 1 N) would be misrecorded as "off the ground", and ref_contact
        # would teach the policy to lift its feet while squatting. For each leg the
        # minimum foot z over the whole run is the planted baseline; z - baseline
        # < 10 mm means planted -- airborne is at least 86 mm higher. The 10 mm
        # accommodates the ~5.6 mm swing of the front forearm F_Link body origin
        # with arm pose when planted (the mesh toe tip stays planted, the body
        # origin moves).
        foot_z = f("foot_pos")[:, :, 2]
        planted_z = foot_z.amin(dim=0, keepdim=True)
        self.contact = (foot_z - planted_z < 0.010).float()

        # foot world frame -> base frame
        foot_w = f("foot_pos")
        rel = foot_w - self.base_pos.unsqueeze(1)
        q_exp = self.base_quat.unsqueeze(1).expand(-1, rel.shape[1], -1).reshape(-1, 4)
        self.foot_b = quat_apply_inverse(q_exp, rel.reshape(-1, 3)).reshape(rel.shape)

        # gravity direction in base frame -- the orientation target the policy
        # observes (what the IMU gives)
        g_w = torch.tensor([[0.0, 0.0, -1.0]], device=device).expand(self.n, 3)
        self.proj_g = quat_apply_inverse(self.base_quat, g_w)

    def deploy_contract(self, lookahead_s, baseline_lead_s: float,
                        go_event: str | None = None,
                        starts_on_entry: bool = False) -> dict:
        """What a board needs to reproduce this reference, and the tables.

        Every number here is read off the loaded reference rather than restated
        in `env_cfg.py`: a rate or a `t_go` typed a second time is a board
        playing a slightly different recording than the one the policy trained
        against, and nothing would say so.

        `baseline_lead_s` is the action path's, not this module's -- see
        `mdp/actions.py`, which samples `q_cmd` one control step ahead because
        the ZOH target is the interval's *end* value.

        What starts the recording on a board is the caller's to say, and at most
        one thing: `go_event`, a button pressed inside the mode, or
        `starts_on_entry`, the policy taking over once the switch-in ramp has
        reached the home pose. Both is refused here as the controller refuses it
        -- one of the two would never happen -- and neither leaves the motion on
        the controller's timer, a bench aid rather than something a person uses.
        """
        if go_event is not None and starts_on_entry:
            raise ValueError(
                f"the jump either starts on entry or waits for {go_event!r}, not "
                f"both: one of the two would never happen"
            )
        return {
            "name": self.path.stem,
            "npz": str(self.path),
            "joint_order": list(self.joint_names),
            "residual_action": True,
            "rec_hz": self.rec_hz,
            "control_hz": self.control_hz,
            "t_go": self.t_go,
            "go_frame": self.go_frame,
            "duration": self.duration,
            "span": self.span,
            "lookahead_s": [float(h) for h in lookahead_s],
            # Which table the residual is added to. `q_cmd`, deliberately -- see
            # the module docstring in `mdp/actions.py`.
            "baseline": "q_cmd",
            "baseline_lead_s": float(baseline_lead_s),
            # The name of the `[[fsm.button]]` that starts this -- a name, not
            # a button. Which control means what belongs to the deploy
            # manifest, as it does for every other binding; this only says
            # which name is ours. `scripts/export.py` drops a `None`.
            "go_event": go_event,
            "starts_on_entry": starts_on_entry,
            "reference": {
                "q": self.q.tolist(),
                "q_cmd": self.q_cmd.tolist(),
            },
        }

    def index_of(self, t_since_go: torch.Tensor) -> torch.Tensor:
        """Continuous frame index for "time elapsed since go".

        Negative times clamp to the go frame (the stand pose) -- an env waiting
        for the command is scored as standing still.
        """
        idx = (self.t_go + t_since_go) / self.dt
        return idx.clamp(float(self.go_frame), float(self.n - 1))

    def phase(self, t_since_go: torch.Tensor) -> torch.Tensor:
        """0 at go, 1 at the end of the reference -- the scalar the policy observes."""
        return (t_since_go / self.span).clamp(0.0, 1.0)

    def sample_cmd(self, t_abs: torch.Tensor) -> torch.Tensor:
        """Interpolate the controller command q_cmd at absolute recording time t
        (counted from the start of the npz).

        t = time_since_go + t_go. The waiting period (negative tsg) lands in the
        recorded preparatory stand; past the end it clamps to the last frame.
        """
        idx = (t_abs * self.control_hz).clamp(0.0, float(self.q_cmd.shape[0] - 1))
        lo = idx.floor().long().clamp(0, self.q_cmd.shape[0] - 1)
        hi = (lo + 1).clamp(0, self.q_cmd.shape[0] - 1)
        w = (idx - lo.float()).unsqueeze(-1)
        return self.q_cmd[lo] * (1.0 - w) + self.q_cmd[hi] * w

    def sample(self, idx: torch.Tensor) -> dict[str, torch.Tensor]:
        """Linearly interpolate every channel at continuous frame index (idx shape (E,))."""
        lo = idx.floor().long().clamp(0, self.n - 1)
        hi = (lo + 1).clamp(0, self.n - 1)
        w = (idx - lo.float()).unsqueeze(-1)

        def lerp(a):
            wa = w if a.dim() == 2 else w.unsqueeze(-1)
            return a[lo] * (1.0 - wa) + a[hi] * wa

        return dict(
            q=lerp(self.q),
            qd=lerp(self.qd),
            base_pos=lerp(self.base_pos),
            base_lin_vel=lerp(self.base_lin_vel),
            foot_b=lerp(self.foot_b),
            proj_g=lerp(self.proj_g),
            contact=self.contact[lo],
            base_quat=self.base_quat[lo],
        )


def get_reference(env, path: Path | str | None = None) -> JumpReference:
    """One instance per env -- loaded once, reused by every reward/obs/event term."""
    if not hasattr(env, "_jump_reference"):
        robot = env.scene["robot"]
        p = Path(path) if path is not None else JUMP_REF_NPZ
        env._jump_reference = JumpReference(p, env.device, list(robot.joint_names))
        r = env._jump_reference
        print(
            f"[jump-ref] {p.name}: {r.n} frames @ {r.rec_hz:g} Hz, {r.duration:.2f} s"
            f" (go at {r.t_go:.2f} s, phase spans {r.span:.2f} s), "
            f"stand base_z {r.stand_base_z:.4f} m"
        )
    return env._jump_reference


def time_since_go(env, command_name: str) -> torch.Tensor:
    """Seconds elapsed since go for this episode, per env. Negative during the wait.

    The go instant is expressed uniformly by the command term's `_go_step` (a
    negative value means RSI -- the env is born mid-jump, so go already happened
    before the episode began), so no branching is needed.
    """
    cmd = env.command_manager.get_term(command_name)
    return (env.episode_length_buf - cmd.go_step).float() * env.step_dt


def ref_state(env, command_name: str, path: Path | None = None):
    """This step's (reference, reference sample, phase, t_since_go).

    Cached on `common_step_counter` so a dozen reward terms share one
    interpolation.
    """
    stamp = int(env.common_step_counter)
    if getattr(env, "_jump_ref_stamp", None) != stamp:
        r = get_reference(env, path)
        tsg = time_since_go(env, command_name)
        env._jump_ref_cache = (r, r.sample(r.index_of(tsg)), r.phase(tsg), tsg)
        env._jump_ref_stamp = stamp
    return env._jump_ref_cache


__all__ = [
    "JUMP_REF_NPZ",
    "REF_DIR",
    "JumpReference",
    "get_reference",
    "ref_state",
    "time_since_go",
]
